stages:
  - deploy-backend
  - deploy-frontend
  - test

deploy-backend:
  stage: deploy-backend
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app="datenbanken-ws22" --api-key=$HEROKU_API_KEY
    - echo "Deployed to Server https://datenbanken-ws22.herokuapp.com"
  only:
    - main

deploy-frontend:
  stage: deploy-frontend
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app="datenbanken-ws22-frontend" --api-key=$HEROKU_API_KEY
    - echo "Deployed to Server https://datenbanken-ws22-frontend.herokuapp.com"
  only:
    - main


test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python
    - cd backend
    - pip install -r requirements.txt
    - python -m unittest test/*.py