stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app="datenbanken-ws22" --api-key=$HEROKU_API_KEY
    - echo "Deployed to Server https://datenbanken-ws22.herokuapp.com"
  environment:
    name: deployment
    url: https://flask-api-staging.herokuapp.com/