DROP INDEX IF EXISTS ERSTSTIMME_KANDIDATUR;

DROP INDEX IF EXISTS ZWEITSTIMME_WAHLKREIS;
DROP INDEX IF EXISTS ZWEITSTIMME_LISTE;
DROP INDEX IF EXISTS ZWEITSTIMME_WAHLKREIS_LISTE;

DROP INDEX IF EXISTS UNGUELTIGE_STIMME_WAHLKREIS;
DROP INDEX IF EXISTS UNGUELTIGE_STIMME_STIMMENTYP;
DROP INDEX IF EXISTS UNGUELTIGE_STIMME_WAHLKREIS_STIMMENTYP;


CREATE INDEX ERSTSTIMME_KANDIDATUR ON ERSTSTIMME (KANDIDATUR);

CREATE INDEX ZWEITSTIMME_WAHLKREIS ON ZWEITSTIMME (WAHLKREIS);
CREATE INDEX ZWEITSTIMME_LISTE ON ZWEITSTIMME (LISTE);
CREATE INDEX ZWEITSTIMME_WAHLKREIS_LISTE ON ZWEITSTIMME (WAHLKREIS, LISTE);

CREATE INDEX UNGUELTIGE_STIMME_WAHLKREIS ON UNGUELTIGE_STIMME (WAHLKREIS);
CREATE INDEX UNGUELTIGE_STIMME_STIMMENTYP ON UNGUELTIGE_STIMME (STIMMENTYP);
CREATE INDEX UNGUELTIGE_STIMME_WAHLKREIS_STIMMENTYP ON UNGUELTIGE_STIMME (STIMMENTYP, WAHLKREIS);

DROP INDEX IF EXISTS ZWEITSTIMMMENERGEBNIS_WAHLKREIS;
DROP INDEX IF EXISTS DIREKTKANDIDATUR_WAHLKREIS;

CREATE INDEX ZWEITSTIMMENERGEBNIS_WAHLKREIS ON ZWEITSTIMMENERGEBNIS (WAHLKREIS);
CREATE INDEX DIREKTKANDIDATUR_WAHLKREIS ON DIREKTKANDIDATUR (WAHLKREIS);