@startuml
class Kandidat {
    String vorname
    String nachname
    char geschlecht
    int alter
    String beruf
}

class Bundesland {
    String name
}

class Partei {
    String name
    int gruendungsjahr
}

class Bundestagswahl{
   int jahr
}

class Bevoelkerung {
    long anzahl
}

class Landesliste {
}


class Listenplatz {
    int position
}

class Wahlkreis {
    int nummer
    String name
}

class Stimme {
    boolean gueltig
}

class Direktkandidatur {
}

Landesliste "1..*" --* "1" Bundesland : < hat
Landesliste "*" --* "1" Partei : < hat
Landesliste "*" --> "1" Bundestagswahl: zur >

Landesliste "1" *-- "1..*" Listenplatz : enthaelt >
Listenplatz "*" --> "1" Kandidat : enthaelt >

Wahlkreis "1..*" --* "1" Bundesland : besteht aus <

Bevoelkerung "*" --* "1" Wahlkreis : < hat
Bevoelkerung "299" --> "1" Bundestagswahl: gueltig fuer >

Direktkandidatur "*" --> "1" Kandidat : von >
Direktkandidatur "*" --* "1" Wahlkreis : < hat
Direktkandidatur "*" --> "0..1" Partei : von >
Direktkandidatur "*" --> "1" Bundestagswahl: zur >

Stimme "*" --> "1" Direktkandidatur : Erststimme >
Stimme "*" --> "1" Landesliste : Zweitstimme >
@enduml