@startuml
class Kandidat {
    String vorname
    String nachname
    char geschlecht
    Date geburtsdatum
    String beruf
}

class Bundesland {
    String name
    boolean osten
}

class Partei {
    String name
    int gruendungsjahr
    String farbe
}

class Bundestagswahl{
   int jahr
}

class Wahlkreisinformation {
    int anzahlMenschen
    int anzahlGemeinden
    int flaeche
    int altersDurchschnitt
}

class Landesliste {
}

class Listenplatz {
    int position
}

class Wahlkreis {
    int nummer
    String name
}

class Stimme {
    boolean erststimmeGueltig
    boolean zweitstimmeGueltig
}

class Direktkandidatur {
}

Landesliste "*" -- "1" Bundesland : in >
Landesliste "*" -- "1" Partei : < reicht ein
Landesliste "*" -- "1" Bundestagswahl: zur >

Landesliste "1" *-- "1..*" Listenplatz : enthaelt >
Listenplatz "*" -- "1" Kandidat : enthaelt >

Wahlkreis "1..*" --* "1" Bundesland : besteht aus <

Wahlkreisinformation "*" --* "1" Wahlkreis : < hat
Wahlkreisinformation "299" -- "1" Bundestagswahl: gueltig fuer >

Direktkandidatur "*" -- "1" Kandidat : von >
Direktkandidatur "*" -- "1" Wahlkreis : < hat
Direktkandidatur "*" -- "0..1" Partei : von >
Direktkandidatur "*" -- "1" Bundestagswahl: zur >

Stimme "*" -- "1" Direktkandidatur : Erststimme >
Stimme "*" -- "1" Landesliste : Zweitstimme >
Stimme "*" -up- "1" Wahlkreis : stammt aus >
@enduml